language: elixir

elixir:
  - 1.9.2

services:
  - postgresql

before_install:
  - chmod +x ./scripts/*

before_script:
  - mix do ecto.create, ecto.migrate

script:
  - mix test
#   - ./scripts/zip_project.sh
#
# deploy:
#   - provider: s3
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     local_dir: aws_deploy
#     skip_cleanup: true
#     bucket: mbdebbeler-apprenticeship-2
#     region: us-east-2
#     on:
#       all_branches: true
#   - provider: codedeploy
#     access_key_id: $AWS_ACCESS_KEY
#     secret_access_key: $AWS_SECRET_KEY
#     bucket: mbdebbeler-apprenticeship-2
#     key: aws_deploy/recipebook.tar.gz
#     bundle_type: tgz
#     application: phoenix_recipe_book
#     deployment_group: apprenticeship
#     wait_until_deployed: true
#     on:
#       all_branches: true
#     region: us-east-2
